package io.github.bekoenig.trymigrate.core.internal;

import java.io.IOException;
import java.net.URISyntaxException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Objects;

/**
 * Utility for resolving output paths within the target directory.
 * <p>
 * Provides consistent path resolution for reports, exports, and other artifacts
 * generated by trymigrate.
 */
public final class OutputPathResolver {

    private final String baseDirProperty;
    private final String subFolder;

    /**
     * Creates a new resolver.
     *
     * @param baseDirProperty system property name for overriding the base directory (nullable)
     * @param subFolder       the subfolder within target (e.g., "trymigrate-lint-reports")
     */
    public OutputPathResolver(String baseDirProperty, String subFolder) {
        this.baseDirProperty = baseDirProperty;
        this.subFolder = subFolder;
    }

    /**
     * Resolves the output path for the given schema.
     *
     * @param schema the schema name
     * @return the resolved output folder path
     */
    public Path resolve(String schema) {
        Path outputFolder = getBaseDir()
                .resolve(subFolder)
                .resolve(Objects.requireNonNullElse(schema, "schema-undefined"));

        try {
            Files.createDirectories(outputFolder);
        } catch (IOException e) {
            throw new IllegalStateException("Failed to create folder: " + outputFolder, e);
        }

        return outputFolder;
    }

    /**
     * Resolves the output file path for the given schema and filename.
     *
     * @param schema   the schema name
     * @param filename the filename
     * @return the resolved output file path
     */
    public Path resolve(String schema, String filename) {
        return resolve(schema).resolve(filename);
    }

    private Path getBaseDir() {
        if (baseDirProperty != null) {
            String property = System.getProperty(baseDirProperty);
            if (property != null) {
                return Path.of(property);
            }
        }
        return getTargetFolder();
    }

    private Path getTargetFolder() {
        try {
            // target folder is parent of system resource folder
            return Path.of(Objects.requireNonNull(ClassLoader.getSystemResource("./")).toURI()).getParent();
        } catch (URISyntaxException e) {
            throw new IllegalStateException("Failed to get root uri for system resources of class loader", e);
        }
    }

}

